require("rh.plugins-setup")
require("rh.core.options")
require("rh.core.keymaps")
require("rh.core.colorscheme")
require("rh.plugins.comment")
require("rh.plugins.nvim-tree")
require("rh.plugins.lualine")
require("rh.plugins.telescope")
require("rh.plugins.nvim-cmp")

require("rh.plugins.lsp.mason")
require("rh.plugins.lsp.lspsaga")
require("rh.plugins.lsp.lspconfig")
require("rh.plugins.lsp.null-is")
require("rh.plugins.autopairs")
require("rh.plugins.treesitter")
require("rh.plugins.gitsigns")
